### ISSUE TITLE
move STRef to Control.Monad.ST.Ref

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-st#16]
Proposal: move STRef to Control.Monad.ST.Ref.

In the spirit of https://github.com/purescript/purescript-arrays/issues/129

Shorten the names of the relevant functions: `writeSTRef` becomes `write`, etc.

Re-export the functions under their old names in `Control.Monad.ST`, with deprecation warnings.

This will require the creation of `Control.Monad.ST.Types`, to avoid cyclical dependencies. The relevant modules can re-export bindings from `Control.Monad.ST.Types`.

**Comment by garyb** [comment]
Resolved in the 0.12 branch.
