### ISSUE TITLE
Global region, take two

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript-st#19]
Previous issue was #7, but that was still about effect rows.

Now that we no longer use effect rows, it is no longer possible to use ST globally by adding `st :: ST a` to the effect row of `main`.

I think that we can abstract over Effect and ST so that code that uses mutation can be used on both global and local state, as follows.

```purescript
foreign import data Global :: Region

effectToST :: Effect ~> ST Global
stToEffect :: ST Global ~> Effect

instance MonadEffect (ST Global) where
  liftEffect = effectToST
```

Now we can abstract over it.

```purescript
class MonadST s m | m -> s where
  liftST :: ST s ~> m

instance monadSTEffect :: MonadST Global Effect where
  liftST = stToEffect

instance monadSTST :: MonadST s ST where
  liftST = id
```

Now, `STRef` and `Ref` can be unified, allowing for code reuse. Similar for `STArray` and something I don't think exists yet (useful for fixing https://github.com/purescript-node/purescript-node-process/issues/8).

```purescript
foreign import data Ref :: Region -> Type -> Type

newRef :: forall s m a. MonadST s m => a -> m (Ref s a)
readRef :: forall s m a. MonadST s m => Ref s a -> m a
writeRef :: forall s m a. MonadST s m => Ref s a -> a -> m Unit
```

Additionally, ST can be used without explicit lifting with monad transformers.

**Comment by garyb** [comment]
Moving everything to use `MonadST` constraints would destroy the ability to optimize `ST` I think (not that it is optimized in the 0.12 RC just now).

Honest question: why/when would you want to do this? I can't think of any situations where I've wanted a non-closed ST.

**Comment by rightfold** [comment]
When you have a library that already uses ST, but you want to use it from Effect (for example STArray).

**Comment by eric-corumdigital** [comment]
Am wanting to use STObject in Effect. Got my upvote.
