### ISSUE TITLE
Release with `v` prefix

### ISSUE THREAD

**Issue by f-f** [purescript/purescript-st#28]
The fact that the latest release doesn't have a `v` prefix is causing a [build failure in package-sets](https://github.com/purescript/package-sets/pull/575#issuecomment-594497207). And indeed, that version number doesn't conform to [the rules for adding a package to the set](https://github.com/purescript/package-sets/blob/master/CONTRIBUTING.md#general)

Could we cut a `v4.2.0` release?

**Comment by hdgarrood** [comment]
Is there a reason to increment the version number? The tag would be pointing at the same commit presumably, so my first thought would have been to call it `v4.1.0`.

**Comment by f-f** [comment]
@hdgarrood I'd just increment the version number to avoid any possible confusion with SemVer ordering. I guess we could be fine with `v4.1.1` too.

**Comment by hdgarrood** [comment]
Fair enough. I think `v4.1.1` is more appropriate, since there are no code changes.

**Comment by hdgarrood** [comment]
Done!

**Comment by garyb** [comment]
Apologies. Not sure why after making hundreds or maybe thousands of library releases I suddenly dropped the `v`. :smile:

**Comment by f-f** [comment]
Thank you both! :slightly_smiling_face:
