### ISSUE TITLE
Implement ST using Ref

### ISSUE THREAD

**Issue by texastoland** [purescript/purescript-st#4]
Continued from [Twitter](https://twitter.com/gb_r/status/758293901648113664).

**Comment by paf31** [comment]
👍 Makes sense, as long as we hide the appropriate constructors. This should allow us to cast a `STRef` to a regular `Ref`, or an `ST` action to a `Ref` action (but not the other way around).

**Comment by texastoland** [comment]
> This should allow us to cast

I'm writing `toRef` and `Unsafe.fromRef` but it makes me wonder whether it'd make more sense to implement `Ref` in terms of `ST` instead of the other way around since it doesn't require anything unsafe?

**Comment by texastoland** [comment]
> This should allow us to cast…

Yeah this is working awesome!

**Comment by garyb** [comment]
Closing this as `Ref` is in `Effect` and `ST` is its own thing now.
