### ISSUE TITLE
Why does Aff not implement MonadST?

### ISSUE THREAD

**Issue by Mateiadrielrafael** [purescript/purescript-st#50]
Is there any particular reason for this? In particular, `purescript-hyrule` bases a lot of the helpers around `MonadST`, so it would be nice to be able to use them directly with `Aff`

**Comment by garyb** [comment]
Moving question to `Aff` since that's where the instance would live 🙂

**Comment by garyb** [comment]
Okay, nevermind. You can't move issues cross-organization.

**Comment by natefaubion** [comment]
I think it's just that MonadST is relatively new and no one has asked for it.

**Comment by Mateiadrielrafael** [comment]
If I'd open a PR for it, would it get merged? If yes, I should open it on the Aff repo, right?

**Comment by JordanMartinez** [comment]
I'd say yeah?

**Comment by JordanMartinez** [comment]
I'm guessing the instance would just be lifting the Effect instance, right? Something like this?
```purs
instance MonadST s Aff where
  liftST = liftEffect <<< liftST
```

**Comment by Mateiadrielrafael** [comment]
Yep!
